### ISSUE TITLE
Problem with name generation

### ISSUE THREAD

**Issue by bergm** [c80k/capnproto-dotnetcore#22]
Hello,

I just stumbled upon the problem that I used the word Proxy appended to an interface name in my schemas, which collides with the automatically generated proxies. As this happend before in a different context I don't remember, I suggest to generate a name which is likely not to be used. Which seams hard, especially with the emphasis of having a nice generated API, but I guess there's no way around in the mid to longterm as one can never assume that the user of the compiler/code generator is able to change a schema. 

But I don't have a good idea, which isn't ugly at the same time. :-(

Cheers

Michael

**Comment by c80k** [comment]
I would consider one of these two options:

1. Detect that two names would collide and make at least one of them unique, e.g. by attaching some postfix. Since the generated Proxy classes are usually not directly used by application code, mangling them would probably have little impact. E.g. the Proxy for interface A might become "AProxyGenerated49ab56fe3" if there is another type definition "AProxy" that prevents the brief name.
2. Use characters that are legal for C# identifiers, but not for capnp identifiers. Especially capnp seems  to reject non-ANSI characters, which opens the opportunity for creative Unicode use. Do you have any favorite Unicode character? Maybe one that relates to Proxy / Skeleton?  ∏ / Σ ? Ⓟ / Ⓢ ? ⌈A⌉ / ⌊A⌋ ? ⾗ / ⾜ ?

**Comment by bergm** [comment]
I think your last idea sounds best. If CapnProto doesn't allow underscore it sounds like the best solution is to use _Proxy and _Skeleton. 👍 It's easy to type and suffiently succinct. Unicode chars might look cool, but then hard to type.

**Comment by c80k** [comment]
Latest push contains a fix for this. It also contains a little bit house keeping: Every generated identifier is supposed to be found in the GeneratorOptions class, to have a single point of maintenance. But until now, this did not apply to "Proxy", "Skeleton" (now "_Proxy", "_Skeleton").
