### ISSUE TITLE
bug in PipeliningSupportExtensions, when signatures of Eager method match

### ISSUE THREAD

**Issue by bergm** [c80k/capnproto-dotnetcore#23]
Hello,

due to the changes in the PipeliningSupportExtensions there's now the problem that when a method with an interface result like in Common.A below is used in two different files, then there will be two definitions with the same Eager signature in the partial class PipeliningSupportExtensions in the namespace.

minimal example:

common.capnp
```capnp
struct Common {
	interface A {
		methodA @0 () -> ();
	}
}
```

a.capnp
```capnp
using Common = import "common.capnp".Common;
struct OuterA {
	interface B {
		methodB @0 () -> (a :Common.A);
	}
}
```

a.capnp.cs
```csharp
...
public static partial class PipeliningSupportExtensions
    {
        static readonly MemberAccessPath Path_methodB_Eager = new MemberAccessPath(0U);
        public static CapnpGen.Common.IA Eager(this Task<CapnpGen.Common.IA> task)
        {
            return (CapnpGen.Common.IA)CapabilityReflection.CreateProxy<CapnpGen.Common.IA>(Impatient.GetAnswer(task).Access(Path_methodB_Eager));
        }
    }
...
```

b.capnp
```capnp
using Common = import "common.capnp".Common;
struct OuterB {
	interface B {
		methodB1 @0 () -> (a :Common.A);
	}
}
```

b.capnp.cs
```csharp
...
public static partial class PipeliningSupportExtensions
    {
        static readonly MemberAccessPath Path_methodB1_Eager = new MemberAccessPath(0U);
        public static CapnpGen.Common.IA Eager(this Task<CapnpGen.Common.IA> task)
        {
            return (CapnpGen.Common.IA)CapabilityReflection.CreateProxy<CapnpGen.Common.IA>(Impatient.GetAnswer(task).Access(Path_methodB1_Eager));
        }
    }
...
```

Cheers, Michael

[bug-reference-same-result-interface-from-multiple-files.zip](https://github.com/c80k/capnproto-dotnetcore/files/3762719/bug-reference-same-result-interface-from-multiple-files.zip)

**Comment by bergm** [comment]
I tried to fix it, but it's only a partial fix which works only if all the project's capnp files are compiled at once, like the MSBuild integration does (I think). In my understanding either it's not really easy (without reading existing schema files/generated code files) to fix in the general incremental compilation case or the pipeline extension has to be done differently. But I'm new to C# so hopefully there is a general easy way.

Also I'm aware that the tests aren't working right now. I guess test.cs(.bin) and the like have to be recreated, but didn't figure yet out how. That's why I didn't create a pull request this time.

**Comment by c80k** [comment]
Fixing this is indeed not easy. I'm not sure whether MSBuild always compiles all files at once (might happen incrementally in some cases). I've been investigating a two-fold approach:

- Don't generate "Eager" methods, but provide them with a generic implementation inside the core runtime. This solves the problem (at the cost of seeing "Eager" extensions on every Task<T>, even if they are not supported) for methods returning at exactly one capability (should be the vast majority).
- Append the capnp file name to the "PipeliningSupportExtensions" class name (to make it unique). This will make the whole thing compile. But certainly, you will get a compiler error as soon as you attempt to invoke an ambiguous extension method: The compiler cannot decide which one method to pick, and you have to fall back to static method invocation syntax. This is, however, much less likely, since we're talking about two (or more) methods returning tuples with equal types.

**Comment by bergm** [comment]
I just start to understand your approach to PromisePipelining a bit better and it seams every approach has it's ugly drawbacks. I guess your second approach sounds best. If it's really just the compiler complaining and forcing the user to switch to the static invocation syntax it sounds good. Then one would hope that this doesn't happen too often and when it happends at least it's somewhat obvious (probably with some documentation). But the name generation can probably get quickly ugly. I guess one would even have to add the path to the capnp filename as potentially the names can also be the same in different directories etc, even if it's all getting increasingly unlikely.

**Comment by c80k** [comment]
...unlikely enough that one might risk a new issue to be opened. :-P

**Comment by bergm** [comment]
Thank you for the fix. 👍
