### ISSUE TITLE
Problem with transfering lists from non-localhost remote systems

### ISSUE THREAD

**Issue by bergm** [c80k/capnproto-dotnetcore#37]
Hi,
I was trying to chase down a problem the last days. I think I narrowed it down to the following setup:

the Cap'n Proto interface
```capnp
struct ClimateData {
    interface ListTests {
        testLI32 @2 () -> (test :List(Int32));
    }
}
```

the PyCapnp implementation of the interface
```python3
class List_Tests(climate_data_capnp.ClimateData.ListTests.Server):
    def __init__(self):
        self.i = 0
    def testLI32(self, **kwargs): # () -> (test1 :List(Int32));
        self.i = self.i + 1
        return [1 for x in range(self.i)]
```

PyCapnp client code to use the interface
```python3
csv_time_series = capnp.TwoPartyClient("some-IP:some-port").bootstrap().cast_as(climate_data_capnp.ClimateData.ListTests)
    receivedBytes = 0
    for i in range(10000):
        testLI32 = csv_time_series.testLI32().wait().test1
        countLI32 = len(testLI32)
        sumLI32 = sum(testLI32)
        sumSollLI32 = countLI32 * 1
        receivedBytes += countLI32 * 4
        print("Count:", countLI32, "ok?:", sumLI32 == sumSollLI32, "received bytes so far:", receivedBytes)
```

C# code to use the interface
```c#
using (TcpRpcClient csvTimeSeriesClient = new TcpRpcClient("some-IP", some-port))
{
    await Task.WhenAll(csvTimeSeriesClient.WhenConnected);

    var ts = csvTimeSeriesClient.GetMain<Mas.Rpc.ClimateData.IListTests>();

    var receivedBytes = 0;
    for (var i = 1; i < 10000; i++)
    {
        var testLI32 = await ts.TestLI32();
        var testLI32_Count = testLI32.Count;
        receivedBytes += testLI32_Count * 4;
        var testLI32_Sum_Soll = testLI32_Count * 1;
        var testLI32_Sum = testLI32.Sum();
        Console.WriteLine("Count: " + testLI32_Count 
            + " ok?: " + (testLI32_Sum == testLI32_Sum_Soll)
            + " received bytes so far: " + receivedBytes);
    }
}
```

My problem is that when I run the python server part on a remote system (no matter if Linux or Windows) the C# client will only receive the List(Int32) from the interface's method if the list is less than 3000 elements long. Above that the list gets received once (has a length), but either the list elements are starting to be zero somewhere in the list or there are different exceptions (this depends a bit on what is actually returned). In the above case there appear these zero elements and the next RPC call simply breaks due to a broken RPC connection. 
At some point I thought it is just the size of the list, but the above code simply increases the size of the list by one element on each call and then around 1000 elements the code stops working. Running the client again against the server in the accumulated state will continue for a few more loops until again the returned list starts to contain zeros and the connection breaks. This also seams to have nothing todo with accumulated received data as rerunning the client multiple times let it continue, but breaks at different list lengths and different transfered amounts of data.
If I run the python server at the same machine and connect to localhost the C# client has no problems. Connecting with the python client shows no problems no matter if the server runs remote or on localhost.
If I return other types like List(List(Float32)), as I did originally, the exceptions happen or the the sublists are empty. Exceptions probably because the decoding simply encounters malformed data.

What puzzles me actually is that localhost works with the C# client as I would expect that the used transport is the same. But maybe capnproto-dotnetcore is doing something internally different in that case and somebody has an idea what's the problem.

I didn't attache a minimal project as it anyway needs a remote system (as far as I can tell), but I hope the above descriptions help so it can be fixed or we figure out what I have to do differently.

Thank you and best regards
Michael

**Comment by c80k** [comment]
Thanks for reporting this issue! I think you found a major bug. Code review revealed something suspicious which should explain that behavior. See [Framing.cs, FillBuffersFromFrames](https://github.com/c80k/capnproto-dotnetcore/blob/a2fc5c01f7f192e17e37e27a4d3e19bf8c6d9b5e/Capnp.Net.Runtime/Framing.cs#L83):

```csharp
static void FillBuffersFromFrames(Memory<ulong>[] buffers, uint segmentCount, BinaryReader reader)
{
  for (uint i = 0; i < segmentCount; i++)
  {
#if NETSTANDARD2_0
 // discussed later
#else
    var buffer = MemoryMarshal.Cast<ulong, byte>(buffers[i].Span);
    reader.Read(buffer);
#endif
  }
}
```

`BinaryReader.Read(Span<byte> buffer)` returns an `int`, which is obviously not used by the code above. Although the method is undocumented I assume that the return value means the same meaning like for similar overloads: _The number of bytes read into buffer. **This might be less than the number of bytes requested if that many bytes are not available**, or it might be zero if the end of the stream is reached._

Now it makes perfect sense: Since localhost does not have an MTU there will never be less bytes available. On real connections, however, the transfer is scattered across multiple packets, and we might observe exactly that. Ugh!

Of course, solution is simple: Design a loop around `Read` which ensures that the whole buffer fills up.

The `NETSTANDARD2_0` branch is only slightly better. Good news: it will never return corrupt data. Bad news: It will fire an `InvalidDataException` when the number of received bytes does not match the expected number. I.e. instead of receiving zeroes, application would crash.

**Comment by bergm** [comment]
Hi,
maybe this was a bit naive, but I tried to replace the dotnetcore section by the the following. Which seams ok in the debugger, but somehow when running it non-interactively it ends up in infinite loops in the do while section at the end. 
Maybe this helps. I can't look into it for the next few days, so I thought I just post it. Probably I misunderstand the use of Span or something else ...

```c#
var buffer = MemoryMarshal.Cast<ulong, byte>(buffers[i].Span);
var bytesRead = reader.Read(buffer);

//check for multiple chunks
if(bytesRead < buffer.Length)
{
	var sliceLength = 0;
	do
	{
		var slice = buffer.Slice(bytesRead);
		sliceLength = slice.Length;
		bytesRead = reader.Read(slice);
	}
	while (bytesRead < sliceLength);
}
```

**Comment by c80k** [comment]
Read may return 0 if the end of the stream was reached. Never mind, fix is under preparation ;-)
