### ISSUE TITLE
MessageBuilder.Create() defaultSegmentSize is not behaving as expected 

### ISSUE THREAD

**Issue by MoodieG** [c80k/capnproto-dotnetcore#46]
Hey,

When I have a Cap'n Proto message with a list size greater than the defaultSegmentSize in the MessageBuilder, the size of second segment in the message Frame ends up being equal to the size of the list which is greater than defaultSegmentSize. 

This is causing issues when my C++ applications tries to read the data. Is this a bug or expected?

I wrote a simple C# application reproducing the issue:
```
static void Main(string[] args)
{
    var message = MessageBuilder.Create();
    var root = message.BuildRoot<TestMessage.WRITER>();

    int size = 200;
    root.Properties.Init(size);
    for (int i = 0; i < size; ++i)
    {
        root.Properties.WriteText(i, "SomeRandomText");
    }

    for (int i = 0; i < message.Frame.Segments.Count; ++i)
    {
        Console.WriteLine($"Segment {i} is of length {message.Frame.Segments[i].Length}" ;
    }
}
```

Cap'n Proto Schema:

```
struct TestMessage
{
    name @0 : Text;
    properties @1 : List(Text);
}
```

**Comment by c80k** [comment]
Yes, this is expected: When the segment allocator attempts to store the list in the first segment it finds that its remaining size is not sufficient and allocates a new segment. Since list data must be stored in a contiguous block it has to choose a size greater than the defaultSegmentSize.

The resulting data organization should be fully understood by the capnproto.org reference implementation. If you get issues there, this would be bug (but probably not due to the segment count/size).

**Comment by MoodieG** [comment]
Thanks for the clarification. It seems like I may be using the C++ API incorrectly. I will have to dig deeper to debug the issue. 

My C++ program is crashing at layout.c++ saying that "Message contains out-of-bounds list pointer". Is the error message too vague or can you take a wild guess what the problem could be? 

On another note, on what basis did you decide to set the default segment length to 128? Are there any disadvantages in increasing the segment size?

**Comment by c80k** [comment]
Maybe there is something wrong with the framing (https://capnproto.org/encoding.html#serialization-over-a-stream).

It is safe to increase the default segment length. 128 (qwords) was just an initial guess. After performance profiling I even decreased it, because smaller allocations seem to give better performance for default workloads.

**Comment by MoodieG** [comment]
That was the issue! I was not padding zeroes if the number of segments was even. Thanks for your help. You may close this issue :)
