### ISSUE TITLE
How to send "untyped" messages?

### ISSUE THREAD

**Issue by bergm** [c80k/capnproto-dotnetcore#53]
Hi,

the persistent.capnp lines [47-54](https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/persistent.capnp#L47) state that it actually doesn't make sense to let all capabilities inherit from ***Persistent*** for all kinds of reasons. Now I'm struggling to send the ***save*** message to a remote capability I know implements the ***Persistent*** interface. On the C# side I capture calls to my C#-side capabilities via the InterceptPolicy, but if I cast a remote capability to the ***Persistent*** interface and try to send the ***save*** message, the runtime (kind of rightly so) complains, that its the the wrong InterfaceId. Manually setting up a Call either failed or I got the same result.
So now I wonder what I'm doing wrong (without understanding the whole implementation) or if the implementation doesn't support it at the moment?

The line expected to work (but potentially fail if the remote side doesn't implement it). At the moment only works for me if remoteCapability in the schema actually inherits from ***Persistent(Text, Text)***.
```csharp
var sturdyRef = (await ((Proxy)remoteCapability).Cast<IPersistent<string, string>>(false).Save(null)).SturdyRef;
```

Any help is appreciated.
Thank you, Michael

**Comment by c80k** [comment]
Hi Michael,

I'm not sure whether I really got your issue: When you write that the cast/call combo works only if the remote cap actually inherits from Persistent(Text, Text), that's exactly what it's supposed to do.

So does your remote cap inherit from Persistent(Text, Text) or not? Could you give some details on the error you see - what exception, what message? I'm also missing the link why you need interception (since a cap may implement multiple interfaces, let's say YourInterface and Persistent(Text, Text) ).

Regards
Christian

**Comment by bergm** [comment]
Hello Christian,
thanks for the quick reply. I'm aware that I can simply declare/inherit the Persistent interface whereever I need it. Now reading the above mentioned description of the Persistent interface in persistent.capnp and the experiences the Sandstorm guys had while trying to use it, I thought I should follow their advice that persistance should be orthogonal to the domain description reflected in the schemas (at least often). I understood that I "simply" have to, but also can, send the save message to these capabilities/interfaces and they have to understand the save message. I think I saw this also in the Sandstorm code, where they send the save message via a lowlevel call. I thought I can do the same using the BareProxy. I also understood that at the wire-level everything is anyway "dynamically typed" and only the implementations make it look like static typing all the way. 

Regarding interception: I was using this to catch calls to capabilities living on the C# side which where supposed to understand save messages (e.g. send from a Python client). But as the schema doesn't explicitly declare the interfaces to inherit from Persistent, I thought I have no way to implement it directly. So I intercept the messages, check for the InterfaceId of Persistent and create a sturdyRef and directly return (Thinking about it, in this particular case I also want that behavior as this happens in a registry which is suppose to return a sturdyRef for a registered capability, not a sturdyRef from the capability itself). If I understood you correctly, I might be able to implement two Capnp interfaces in C#? Hadn't thought about it, but I had a differnt use case.

But my trouble is to do it in the other direction. I have a Python capability (in this case via multiple inheritance implementing the main interface and Persistent, but the C# side only gets a capability of the main interface type (which doesn't inherit from Persistent). And how to send the save message to the Python side? 

Does this now make more sense?

Thanks for your help and best regards, Michael

**Comment by c80k** [comment]
Yes, the C# side also supports implementing multiple interfaces in a capability.
The scenario which you describe is actually supposed to work: Since the C# side has no knowledge about the actual interfaces implemented at the Python side, it will believe you when you Cast<> your cap to IPersistent and send the call to the Python side. If you get a response from there, complaining about a wrong interface ID, probably the Python side has a configuration problem?

Regards
Christian

**Comment by bergm** [comment]
Yes, you are right. I checked it again and the error is caused on the Python side. The error is produced by capability.c++, so in libcapnp. At least I learned more about the implementations. Thanks a lot for your quick help. Is this actually the best way to ask questions regarding your implementation?
Cheers and regards, Michael

**Comment by c80k** [comment]
Great! Asking questions here is fine for me.
Regards, Christian
