### ISSUE TITLE
Not on Chocolatey

### ISSUE THREAD

**Issue by griestopf** [c80k/capnproto-dotnetcore#6]
The Readme.md explains how to install this project from Chocolatey,
```ps
choco install capnpc-csharp
```
No such package seems to exist (yet?) at https://chocolatey.org/packages

**Comment by c80k** [comment]
The package is submitted, but review is pending, see https://chocolatey.org/packages/capnpc-csharp/1.0.0 for .NET Core Runtime-dependent deployment, and https://chocolatey.org/packages/capnpc-csharp-win-x86/1.0.0 for self-contained deployment.

It has been taking several iterations to get is past the review process, and I hope that it finally meets the criteria.

Instead of obtaining it from chocolatey.org you may also

- Clone the master branch
- run scripts\capnpc-csharp-pack.ps1 to create the packages for your own purpose
- run either scripts\capnpc-csharp-install.ps1 or scripts\capnpc-csharp-install-win-x86.ps1 to install it locally.

I'll write a short notice here as soon as the packages have been finally published.

**Comment by c80k** [comment]
Intermediate update: Crux of the matter is package verification. My original idea was to instruct reviewers to rebuild the packages from this repo and let them do a binary comparison of the pushed assemblies with their self-built binaries. My hope was that they would be identical. It turned out that this is not the case, even if the reviewer and I use exactly the same build environment (the Chocolatey verification environment). I suspect it's due to the PDBs (which probably contain some build timestamp in their file content). That's a pitty, since this approach would have been the ultimate proof that the binaries I pushed really do not contain anything else but this codebase.

New approach is to setup a CI, provide the binaries as official GitHub release, and base the verification on comparing the package content with the binaries released here.

**Comment by c80k** [comment]
Done. Pre-release v1.0.71 made its way through the Chocolatey approval process.

**Comment by KubaO** [comment]
Congrats on getting this into Chocolatey!
